.PHONY: clean All

All:
	@echo "----------Building project:[ New_Year_and_Hurry - Debug ]----------"
	@cd "New_Year_and_Hurry" && "$(MAKE)" -f  "New_Year_and_Hurry.mk"
clean:
	@echo "----------Cleaning project:[ New_Year_and_Hurry - Debug ]----------"
	@cd "New_Year_and_Hurry" && "$(MAKE)" -f  "New_Year_and_Hurry.mk" clean
