.PHONY: clean All

All:
	@echo "----------Building project:[ Pair_of_numbers_of_a_sun - Debug ]----------"
	@cd "Pair_of_numbers_of_a_sun" && "$(MAKE)" -f  "Pair_of_numbers_of_a_sun.mk"
clean:
	@echo "----------Cleaning project:[ Pair_of_numbers_of_a_sun - Debug ]----------"
	@cd "Pair_of_numbers_of_a_sun" && "$(MAKE)" -f  "Pair_of_numbers_of_a_sun.mk" clean
